#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")" # Find out where we are.
# Use LD_LIBRARY_PATH instead of patching the binary. Needed to load libsteam_api.so .
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HERE/usr/lib/
exec $HERE/usr/bin/microlaunch "$@"

